### ISSUE TITLE
application crash with exception

### ISSUE THREAD

**Issue by gagarin55** [ScorexProject/Lagonaki#3]
If there is no "app" section in settings.config application crash with:

Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'app'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)

**Comment by catena2w** [comment]
Cannot reproduce this bug, can you provide more info? And full stacktrace
